### ISSUE TITLE
Puede interesarte este dataset

### ISSUE THREAD

**Issue by pablodz** [loreabad6/covid19EC#1]
Hola, junto con una organización sin fines de lucro se está centralizando la información de contagiados/muertos/recuperados covid-19 de todos los páises de latinoamérica. Asímismo, usamos ISO 3166-2 para el código de departamentos/provincias/regiones de cada país. La información se actualiza frecuentemente.

Saludos.

**Comment by loreabad6** [comment]
Hola @ZurMaD, me podrías colocar el link por favor? Seguro le daré un vistazo!

**Comment by pablodz** [comment]
https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/ 
Olvide colorcarlo en el post.

**Comment by loreabad6** [comment]
Gracias! Le echaré un vistazo!
